# Generated by Django 4.0.5 on 2022-07-02 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0002_initial'),
        ('userchoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=False, verbose_name='주문완료')),
                ('pay_check', models.CharField(choices=[('현금', '현금'), ('카드', '카드'), ('계좌이체', '계좌이체')], default='', max_length=4, verbose_name='결제방식')),
                ('delivery_state', models.CharField(choices=[('배송준비 중', '배송준비 중'), ('배송 중', '배송 중'), ('배송완료', '배송완료')], default='배송준비 중', max_length=50, verbose_name='배송상태')),
            ],
            options={
                'db_table': 'order_list',
            },
        ),
        migrations.RemoveField(
            model_name='cart',
            name='delivery_state',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pay_check',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='the_time_payed',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='고객'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productoption', verbose_name='상품옵션'),
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_time_payed', models.DateTimeField(auto_now_add=True, verbose_name='구매완료 시간')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userchoice.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userchoice.cart', verbose_name='장바구니'),
        ),
    ]
