# Generated by Django 4.0.5 on 2022-07-04 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userchoice', '0002_order_remove_cart_delivery_state_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlist',
            name='order',
        ),
        migrations.AddField(
            model_name='orderlist',
            name='cart',
            field=models.ManyToManyField(to='userchoice.cart', verbose_name='장바구니'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='complete',
            field=models.BooleanField(default=True, verbose_name='주문완료'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='delivery_state',
            field=models.CharField(choices=[('배송준비 중', '배송준비 중'), ('배송 중', '배송 중'), ('배송완료', '배송완료')], default='배송준비 중', max_length=50, verbose_name='배송상태'),
        ),
        migrations.AddField(
            model_name='orderlist',
            name='pay_check',
            field=models.CharField(choices=[('현금', '현금'), ('카드', '카드'), ('계좌이체', '계좌이체')], default='', max_length=4, verbose_name='결제방식'),
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
