# Generated by Django 4.0.5 on 2022-07-04 04:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userchoice', '0003_remove_orderlist_order_orderlist_cart_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderlist',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='고객'),
        ),
    ]
