# Generated by Django 4.0.5 on 2022-08-09 16:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_paid', models.BooleanField(default=False, verbose_name='지불여부')),
            ],
            options={
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'like',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40, verbose_name='상품명')),
                ('thumbnail', models.ImageField(upload_to='product/thumbnail', verbose_name='썸네일')),
                ('desc', models.TextField(blank=True, verbose_name='설명')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='수정시간')),
                ('show_expired_date', models.DateField(verbose_name='노출 종료일')),
                ('stock', models.IntegerField(verbose_name='재고')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화 여부')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.category')),
                ('product_like', models.ManyToManyField(to='product.like', verbose_name='좋아요')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductOption',
            fields=[
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='product.product', verbose_name='상품')),
                ('options', models.CharField(max_length=50, verbose_name='옵션')),
                ('quantity', models.IntegerField(verbose_name='수량')),
                ('sizes', models.CharField(max_length=10, verbose_name='사이즈')),
                ('price', models.IntegerField(verbose_name='가격')),
            ],
            options={
                'db_table': 'product_option',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(blank=True, verbose_name='평점')),
                ('content', models.TextField(blank=True, verbose_name='내용')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='등록시간')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='상품')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자')),
            ],
            options={
                'db_table': 'review',
            },
        ),
        migrations.CreateModel(
            name='OrderList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('the_time_payed', models.DateTimeField(auto_now_add=True, verbose_name='구매완료 시간')),
                ('pay_check', models.CharField(choices=[('현금', '현금'), ('카드', '카드'), ('계좌이체', '계좌이체')], default='', max_length=4, verbose_name='결제방식')),
                ('delivery_state', models.CharField(choices=[('배송준비 중', '배송준비 중'), ('배송 중', '배송 중'), ('배송완료', '배송완료')], default='배송준비 중', max_length=50, verbose_name='배송상태')),
                ('cart', models.ManyToManyField(to='product.cart', verbose_name='장바구니')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='고객')),
            ],
        ),
        migrations.AddField(
            model_name='like',
            name='product_like',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='상품'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='작성자'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.product', verbose_name='상품'),
        ),
        migrations.AddField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='고객'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product_option',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.productoption', verbose_name='상품옵션'),
        ),
    ]
