# Generated by Django 4.0.5 on 2022-06-25 12:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_name', models.CharField(max_length=50)),
                ('product_options', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.productoption')),
            ],
            options={
                'db_table': 'product_option_size',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_name', models.CharField(max_length=50)),
                ('product_options', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='product.productoption')),
            ],
            options={
                'db_table': 'product_option_name',
            },
        ),
    ]
